spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/drone_service_local_db?currentSchema=public&stringtype=unspecified
    username: drone_service
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      default_schema: public
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              mod:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
